### ISSUE TITLE
[Suggestion/Enhancement] Color Changes

### ISSUE THREAD

**Issue by AyrianaWoW** [shagu/ShaguInventory#3]
I've created a (temporary) fork with a preview of what it looks like:
![WoWScrnShot_092424_011847](https://github.com/user-attachments/assets/4d3aba52-94b2-419b-b212-485468609500)

I believe these changes greatly enhance and improve visibility, legibility, and comfort for most end-users.  Colors could further be adjusted as needed depending on specific desires/needs.  If you'd like to add a 'color picker' with in-game UI/GUI that would be fantastic but a bit complex for a simple add-on.

Change line 103 of ShaguInventory.lua:

From:
```lua
GameTooltip:AddDoubleLine(char .. " |cff556677[" .. slot .. "]", count, 0.65, 0.75, 0.85, 0.65, 0.75, 0.85)
```

To:
```lua
GameTooltip:AddDoubleLine("|cffffbd00" .. char .. " |cffb75bff[" .. slot .. "]", count, 1, 1, 1, 1, 1, 1)
```

Change line 108 of ShaguInventory.lua:

From:
```lua
GameTooltip:AddDoubleLine("Total:", totalCount, 0, 0.8, 1, 0, 0.8, 1)
```

To:
```lua
GameTooltip:AddDoubleLine("Total:", totalCount, 0, 1, 1, 0, 1, 1)
```

**Comment by shagu** [comment]
Hello, thanks for your suggestsion.

But I personally like the less colorful version more. I already have enough different colors on every tooltip from all the other addons. Having everything from this addon being the same color-tint, helps me to differentiate it from all the other additional information. 

Regarding the color picker: I'd prefer to keep it simple. Moving all color codes and texts up to the top of the addon code, so that people can adjust it more easily would make more sense here. Please send a pull request if you decide to do so, because I won't have much time for it the next weeks and will probably forget about it after.

Or if you really wish to turn the addon into something big, with a color picker and a configuration UI, please feel free to take over the repository and do so :)

**Comment by AyrianaWoW** [comment]
I understand and appreciate your response.
I am very careful moving sections of code around because the way Lua code works tends to require declaring variables and everything before doing functions and doing so in a certain order.
I'll keep my fork as a potential alternative and possibly add it to the Turtle WoW Wiki as a 'colorized' version for those who enjoy it.  I don't plan to continue working on this as I've got a lot of projects that I work on ;)
